//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfHexaEditor.Properties {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WpfHexaEditor.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Bookmarks.
        /// </summary>
        public static string BookmarksString {
            get {
                return ResourceManager.GetString("BookmarksString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Byte action.
        /// </summary>
        public static string ByteActionString {
            get {
                return ResourceManager.GetString("ByteActionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Byte.
        /// </summary>
        public static string ByteString {
            get {
                return ResourceManager.GetString("ByteString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cancel long process.
        /// </summary>
        public static string CancelLongProcessString {
            get {
                return ResourceManager.GetString("CancelLongProcessString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Click to cancel long process..
        /// </summary>
        public static string CancelLongProcessToolTipString {
            get {
                return ResourceManager.GetString("CancelLongProcessToolTipString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cancel.
        /// </summary>
        public static string CancelString {
            get {
                return ResourceManager.GetString("CancelString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Clear bookmark.
        /// </summary>
        public static string ClearBookMarkString {
            get {
                return ResourceManager.GetString("ClearBookMarkString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Click to go to at position..
        /// </summary>
        public static string ClickToGoAtPositionString {
            get {
                return ResourceManager.GetString("ClickToGoAtPositionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Copy as ASCII.
        /// </summary>
        public static string CopyAsASCIIString {
            get {
                return ResourceManager.GetString("CopyAsASCIIString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Copy as decimal.
        /// </summary>
        public static string CopyAsDecimalString {
            get {
                return ResourceManager.GetString("CopyAsDecimalString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Copy as hexadecimal.
        /// </summary>
        public static string CopyAsHexadecimalString {
            get {
                return ResourceManager.GetString("CopyAsHexadecimalString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à TBL string (character file loaded).
        /// </summary>
        public static string CopyAsTBLString {
            get {
                return ResourceManager.GetString("CopyAsTBLString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Copy selection as ....
        /// </summary>
        public static string CopySelectionAsString {
            get {
                return ResourceManager.GetString("CopySelectionAsString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Count of.
        /// </summary>
        public static string CountOfString {
            get {
                return ResourceManager.GetString("CountOfString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Default TBL.
        /// </summary>
        public static string DefaultTBLString {
            get {
                return ResourceManager.GetString("DefaultTBLString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Delete.
        /// </summary>
        public static string DeleteString {
            get {
                return ResourceManager.GetString("DeleteString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Description.
        /// </summary>
        public static string DescriptionString {
            get {
                return ResourceManager.GetString("DescriptionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &lt;end&gt;.
        /// </summary>
        public static string EndTagString {
            get {
                return ResourceManager.GetString("EndTagString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enter hexadecimal value ....
        /// </summary>
        public static string EnterHexValueMsgString {
            get {
                return ResourceManager.GetString("EnterHexValueMsgString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Fill selection with byte....
        /// </summary>
        public static string FillSelectionString {
            get {
                return ResourceManager.GetString("FillSelectionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Byte to search.
        /// </summary>
        public static string FindByteString {
            get {
                return ResourceManager.GetString("FindByteString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Find all occurence of selection.
        /// </summary>
        public static string FindSelectionString {
            get {
                return ResourceManager.GetString("FindSelectionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à First byte.
        /// </summary>
        public static string FirstByteString {
            get {
                return ResourceManager.GetString("FirstByteString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Hex.
        /// </summary>
        public static string HexString {
            get {
                return ResourceManager.GetString("HexString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Kb.
        /// </summary>
        public static string KBTagString {
            get {
                return ResourceManager.GetString("KBTagString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Lenght.
        /// </summary>
        public static string LenghtString {
            get {
                return ResourceManager.GetString("LenghtString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ln.
        /// </summary>
        public static string LineStatusBarTagString {
            get {
                return ResourceManager.GetString("LineStatusBarTagString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &lt;ln&gt;.
        /// </summary>
        public static string LineTagString {
            get {
                return ResourceManager.GetString("LineTagString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Long.
        /// </summary>
        public static string LongString {
            get {
                return ResourceManager.GetString("LongString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Mb.
        /// </summary>
        public static string MBTagString {
            get {
                return ResourceManager.GetString("MBTagString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ok.
        /// </summary>
        public static string OkString {
            get {
                return ResourceManager.GetString("OkString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Paste without inserting.
        /// </summary>
        public static string PasteNotInsertString {
            get {
                return ResourceManager.GetString("PasteNotInsertString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Position.
        /// </summary>
        public static string PositionString {
            get {
                return ResourceManager.GetString("PositionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Replace by byte.
        /// </summary>
        public static string ReplaceByByteString {
            get {
                return ResourceManager.GetString("ReplaceByByteString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Replace byte in selection....
        /// </summary>
        public static string ReplaceSelectionString {
            get {
                return ResourceManager.GetString("ReplaceSelectionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Select all.
        /// </summary>
        public static string SelectAllString {
            get {
                return ResourceManager.GetString("SelectAllString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Set bookmark.
        /// </summary>
        public static string SetBookMarkString {
            get {
                return ResourceManager.GetString("SetBookMarkString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à TBL.
        /// </summary>
        public static string TBLString {
            get {
                return ResourceManager.GetString("TBLString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à This string are not hex.
        /// </summary>
        public static string ThisStringAreNotHexString {
            get {
                return ResourceManager.GetString("ThisStringAreNotHexString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Undo.
        /// </summary>
        public static string UndoString {
            get {
                return ResourceManager.GetString("UndoString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Value.
        /// </summary>
        public static string ValueString {
            get {
                return ResourceManager.GetString("ValueString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à An error is occurs when writing..
        /// </summary>
        public static string WritingErrorExeptionString {
            get {
                return ResourceManager.GetString("WritingErrorExeptionString", resourceCulture);
            }
        }
    }
}
